project_id = "gvftvswyrevummbvyhxa"

[functions.fetch-news]
verify_jwt = false

[functions.send-task-notification]
verify_jwt = true

[functions.get-oauth-config]
verify_jwt = false

[functions.oauth-hmrc]
verify_jwt = true

[functions.b2b-form-submit]
verify_jwt = false

[functions.oauth-twitter]
verify_jwt = false

[functions.oauth-twitter-request]
verify_jwt = false

[functions.oauth-linkedin]
verify_jwt = false

[functions.oauth-facebook]
verify_jwt = false

[functions.oauth-icloud-calendar]
verify_jwt = false

[functions.oauth-outlook-calendar]
verify_jwt = false

[functions.workflow-twitter-post]
verify_jwt = true

[functions.workflow-linkedin-post]
verify_jwt = true

[functions.oauth-onedrive]
verify_jwt = false

[functions.workflow-send-email]
verify_jwt = false