project_id = "gvftvswyrevummbvyhxa"

[functions.fetch-news]
verify_jwt = false

[functions.send-task-notification]
verify_jwt = true

[functions.get-oauth-config]
verify_jwt = false

[functions.oauth-hmrc]
verify_jwt = true

[functions.b2b-form-submit]
verify_jwt = false